# http://about.travis-ci.org/docs/user/languages/python/
dist: xenial
language: python
python:
  - "3.6"

install:
  - pip install -U -r requirements.txt

script:
  - doit build-core build-extras build-mappings

