# http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
  - "3.6"

install:
  - pip install -U -r requirements.txt --process-dependency-links

script:
  - doit build-core build-extras

