---
version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    backupCount: 3
    level: INFO
    formatter: simple
    filename: 'dodo.log'
root:
  level: INFO
  handlers: ['file']

